<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CScore\CScore.csproj" />
    <ProjectReference Include="..\OpenCS.OpenSees\OpenCS.OpenSees.csproj" />
    <ProjectReference Include="..\OpenCS.Gmsh\OpenCS.Gmsh.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
