<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CScore\CScore.csproj" />
    <ProjectReference Include="..\OpenCS.OpenSees\OpenCS.OpenSees.csproj" />
    <ProjectReference Include="..\OpenCS.Gmsh\OpenCS.Gmsh.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>$(OpenCSTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenCS.OpenSees.Tests" />
  </ItemGroup>

</Project>
